config/routes.rb
# frozen_string_literal: true

require 'sidekiq/web'

Rails.application.routes.draw do
  authenticate :user, ->(u) { u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  use_doorkeeper
  devise_for :users, controllers: { omniauth_callbacks: 'oauth_callbacks' }

  root to: 'questions#index'

  get '/user/recieve_email', to: 'users#recieve_email', as: 'recieve_email'
  post '/user/set_email', to: 'users#set_email', as: 'set_email'
  get '/search', to: 'searchs#search'

  concern :voted do
    member do
      patch :vote_up
      patch :vote_down
    end
  end

  resources :attachments, only: %i[destroy]

  resources :rewards, only: %i[index]

  resources :questions, concerns: [:voted] do
    resources :answers, concerns: [:voted], shallow: true do
      patch :mark_as_best, on: :member
      resources :comments, only: %i[create destroy], defaults: { commentable: 'answer' }
    end
    resources :comments, only: %i[create destroy], defaults: { commentable: 'question' }
    resources :subscriptions, only: %i[create destroy], shallow: true
  end

  namespace :api do
    namespace :v1 do
      resources :profiles, only: %i[index] do
        get :me, on: :collection
      end

      resources :questions do
        resources :answers, shallow: true
      end
    end
  end

  mount ActionCable.server => '/cable'
end

app/models/question.rb
# frozen_string_literal: true

class Question < ApplicationRecord
  include Linkable
  include Votable
  include Commentable

  after_create :calculate_reputation

  has_many :answers, dependent: :nullify
  has_many :subscriptions, dependent: :destroy
  has_one :reward, dependent: :destroy
  belongs_to :best_answer, class_name: 'Answer', optional: true, dependent: :destroy
  belongs_to :user, touch: true

  has_many_attached :files

  accepts_nested_attributes_for :reward, reject_if: :all_blank

  validates :title, :body, presence: true

  after_create :create_subscription

  def mark_as_best(answer)
    transaction do
      update!(best_answer: answer)
      reward&.update!(user: answer.user)
    end
  end

  def other_answers
    answers.where.not(id: best_answer_id)
  end

  private

  def create_subscription
    subscriptions.create!(user: user)
  end

  def calculate_reputation
    ReputationJob.perform_later(self)
  end
end

app/controllers/api/v1/questions_controller.rb
# frozen_string_literal: true

module Api
  module V1
    class QuestionsController < Api::V1::BaseController
      helper_method :question

      authorize_resource class: Question

      def index
        @questions = Question.all
        render json: @questions, each_serializer: QuestionsSerializer
      end

      def show
        render json: question
      end

      def create
        @question = current_resource_owner.questions.new(question_params)
        if @question.save
          render json: @question
        else
          render json: { errors: @question.errors }, status: :unprocessable_entity
        end
      end

      def update
        if question.update(question_params)
          render json: question
        else
          render json: { errors: question.errors }, status: :unprocessable_entity
        end
      end

      def destroy
        if question.destroy
          render json: question
        else
          render json: { errors: question.errors }, status: :unprocessable_entity
        end
      end

      private

      def question
        @question ||= Question.find(params[:id])
      end

      def question_params
        params.require(:question).permit(:title, :body)
      end
    end
  end
end

app/controllers/questions_controller.rb
# frozen_string_literal: true

class QuestionsController < ApplicationController
  include Voted

  before_action :authenticate_user!, except: %i[index show]
  before_action :set_subscription, only: %i[show update]
  after_action :publish_question, only: [:create]
  helper_method :question

  def index
    @questions = Question.all
  end

  def show
    @answer = Answer.new
    @answer.links.new
    @best_answer = question.best_answer
    @other_answers = question.other_answers
    set_gon
  end

  def new
    question.links.new
  end

  def edit; end

  def create
    @question = current_user.questions.new(question_params)
    if @question.save
      redirect_to @question, notice: 'Your question succeffully created.'
    else
      render :new
    end
  end

  def update
    if question.update(question_params)
      redirect_to @question
    else
      render :edit
    end
  end

  def destroy
    question.destroy
    redirect_to questions_path, notice: 'Your question successfully deleted!'
  end

  private

  def set_gon
    gon.question_id = @question.id
    gon.current_user_id = current_user&.id
  end

  def publish_question
    return if @question.errors.any?

    ActionCable.server.broadcast(
      'questions',
      ApplicationController.render(
        partial: 'questions/question',
        locals: {
          question: @question
        }
      )
    )
  end

  def question
    @question ||= params[:id] ? Question.with_attached_files.find(params[:id]) : Question.new
  end

  def set_subscription
    @subscription ||= current_user&.subscriptions&.find_by(question: question)
  end

  def question_params
    params.require(:question).permit(:title,
                                     :body,
                                     files: [],
                                     links_attributes: %i[id name url _destroy done],
                                     reward_attributes: %i[id title image])
  end
end

app/helpers/questions_helper.rb
# frozen_string_literal: true

module QuestionsHelper
end

app/views/questions/_form.html.slim
= form_with model: question, local: true do |f|
  .card-body
    = render 'shared/errors', resource: question
    .question
      div
        = f.label :title
        = f.text_field :title, class: 'form-control'
      div
        = f.label :body
        = f.text_area :body, class: 'form-control'
      .row
        .col-6
          hr
          .reward
            p Reward:
            = render 'rewards/reward', resource: question.reward
            = f.fields_for :reward, question.build_reward do |reward|
              = render 'rewards/form', f: reward
        .col-6
            hr
            = render 'attachments/attachments', resource: question, edit_path: true
            = f.label :files
            = f.file_field :files, class: 'form-control-file', multiple: true, direct_upload: true

    div
      hr
      .row
        .col-6
          p Links :
          = f.fields_for :links do |link|
            = render 'shared/link_fields', f: link
          .links
            = link_to_add_association 'add link', f, :links, partial: 'shared/link_fields', class: 'btn btn-sm btn-success'
    
  .card-footer
    = f.submit 'Ask', class: "actions btn  btn-sm btn-primary"
    - if question.new_record?
      = link_to "Back", questions_path, class: 'btn btn-sm btn-secondary '
    - else
      = link_to "Back", question, class: 'btn btn-sm btn-secondary '

app/views/questions/_question.html.slim
.row
  .col-1.small.border-right
    = question.rating
  .col-9
    = link_to question.title, question_path(question)
  .col-2.border-left.small
    = image_tag url_for(question.reward.image), size: "30", alt: "#{question.reward.image.filename}" if question.reward.present?

app/views/questions/edit.html.slim
.card
  .card-header
    h2 Edit question
  = render 'questions/form'

app/views/questions/index.html.slim
- if can?(:create, Question)
  = link_to 'Ask question', new_question_path, class: 'btn btn-light'
- cache collection_cache_key_for(Question) do
  .questions
    = render @questions

app/views/questions/new.html.slim
.card
  .card-header
    h1 Create question
  = render 'questions/form'

app/views/questions/show.html.slim
.card-header
  .card-title
    .row
      - cache ['title_for', question] do
        .col-md-8
          .small.text-left Title:
          = question.title
          .small.text-left Author:
          = question.user.email
              
        .col-md-2.span.small
          - if question.reward
            .small.text-center Reward for best answer:
          = render 'rewards/reward', resource: question.reward
      .col-md-1.span.small
        .subscription
          - if can? :create, Subscription
              = render 'subscriptions/subscription', resource: question

.card-body.bg-light
  - cache ['body_for', question] do
    .row
      .col-md-2.border-right
        = render 'shared/vote', resource: question
      .col-md-10
        = question.body
        = render 'attachments/attachments', resource: question, edit_path: false
        = render 'shared/link', resource: question

  .row
    .col-md-10      
      - if can? :update, question
        .text-left
          br
          = link_to 'Edit question', edit_question_path(@question), class: 'btn btn-sm btn-outline-warning edit_question'
          - if can? :destroy, question
            = link_to 'Delete question', question_path(@question), method: :delete, class: 'btn btn-sm btn-outline-danger', data: { confirm: 'Are you sure?'}

  #question_comments
    = render 'comments/comments', resource: question
    br
    - if current_user
      = render 'comments/form', resource: question

.answers
  h2 Answers:
  .container.border.border-info.p-2.bg-light
    = render 'answers/answers', best_answer: @best_answer, other_answers: @other_answers

    .answer-errors
      = render 'shared/errors', resource: @answer
div
  br
-if can? :create, Answer
  - cache ['answer_for', question] do
    .new-answer.container.border.border-info
        = render 'answers/form'