config/routes.rb
# frozen_string_literal: true

require 'sidekiq/web'

Rails.application.routes.draw do
  authenticate :user, ->(u) { u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  use_doorkeeper
  devise_for :users, controllers: { omniauth_callbacks: 'oauth_callbacks' }

  root to: 'questions#index'

  get '/user/recieve_email', to: 'users#recieve_email', as: 'recieve_email'
  post '/user/set_email', to: 'users#set_email', as: 'set_email'
  get '/search', to: 'searchs#search'

  concern :voted do
    member do
      patch :vote_up
      patch :vote_down
    end
  end

  resources :attachments, only: %i[destroy]

  resources :rewards, only: %i[index]

  resources :questions, concerns: [:voted] do
    resources :answers, concerns: [:voted], shallow: true do
      patch :mark_as_best, on: :member
      resources :comments, only: %i[create destroy], defaults: { commentable: 'answer' }
    end
    resources :comments, only: %i[create destroy], defaults: { commentable: 'question' }
    resources :subscriptions, only: %i[create destroy], shallow: true
  end

  namespace :api do
    namespace :v1 do
      resources :profiles, only: %i[index] do
        get :me, on: :collection
      end

      resources :questions do
        resources :answers, shallow: true
      end
    end
  end

  mount ActionCable.server => '/cable'
end

app/models/ability.rb
# frozen_string_literal: true

class Ability
  include CanCan::Ability

  attr_reader :user

  def initialize(user)
    @user = user
    if user
      user.admin? ? admin_abilities : user_abilities
    else
      guest_abilities
    end
  end

  private

  def guest_abilities
    can :read, :all
    can :recieve_email, User
    can :set_email, User
    can :search, :all
  end

  def admin_abilities
    can :manage, :all
  end

  def user_abilities
    guest_abilities

    can :me, User

    can :index, User

    can :create, [Question, Answer, Comment, Subscription]

    can :update, [Question, Answer], user_id: user.id

    can :destroy, [Question, Answer, Comment, Subscription], user_id: user.id

    can %i[vote_up vote_down], [Question, Answer] do |votable|
      !user.author?(votable)
    end

    can :destroy, ActiveStorage::Attachment do |file|
      user.author?(file.record)
    end

    can :mark_as_best, Answer, question: { user_id: user.id }
  end
end

app/models/answer.rb
# frozen_string_literal: true

class Answer < ApplicationRecord
  include Linkable
  include Votable
  include Commentable

  belongs_to :question, touch: true
  belongs_to :user, touch: true

  has_many_attached :files

  validates :body, presence: true

  after_create :new_answer_notification

  private

  def new_answer_notification
    NotificationJob.perform_later(self)
  end
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/authorization.rb
# frozen_string_literal: true

class Authorization < ApplicationRecord
  belongs_to :user, touch: true

  validates :provider, :uid, presence: true
end

app/models/comment.rb
# frozen_string_literal: true

class Comment < ApplicationRecord
  belongs_to :user, touch: true
  belongs_to :commentable, polymorphic: true, touch: true

  validates :body, :user, :commentable_id, presence: true
end

app/models/link.rb
# frozen_string_literal: true

class Link < ApplicationRecord
  belongs_to :linkable, polymorphic: true, touch: true

  validates :name, :url, presence: true
  validates :url, format: { with: URI::DEFAULT_PARSER.make_regexp(%w[http https]) }

  def gist?
    url.match?(/gist.github.com/)
  end
end

app/models/question.rb
# frozen_string_literal: true

class Question < ApplicationRecord
  include Linkable
  include Votable
  include Commentable

  after_create :calculate_reputation

  has_many :answers, dependent: :nullify
  has_many :subscriptions, dependent: :destroy
  has_one :reward, dependent: :destroy
  belongs_to :best_answer, class_name: 'Answer', optional: true, dependent: :destroy
  belongs_to :user, touch: true

  has_many_attached :files

  accepts_nested_attributes_for :reward, reject_if: :all_blank

  validates :title, :body, presence: true

  after_create :create_subscription

  def mark_as_best(answer)
    transaction do
      update!(best_answer: answer)
      reward&.update!(user: answer.user)
    end
  end

  def other_answers
    answers.where.not(id: best_answer_id)
  end

  private

  def create_subscription
    subscriptions.create!(user: user)
  end

  def calculate_reputation
    ReputationJob.perform_later(self)
  end
end

app/models/reward.rb
# frozen_string_literal: true

class Reward < ApplicationRecord
  belongs_to :question, touch: true
  belongs_to :user, optional: true, touch: true

  validates :title, presence: true
  validates :image, attached: true, content_type: %i[png jpeg jpg]

  has_one_attached :image
end

app/models/subscription.rb
# frozen_string_literal: true

class Subscription < ApplicationRecord
  belongs_to :user, touch: true
  belongs_to :question, touch: true
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable,
         :omniauthable, omniauth_providers: %i[github vkontakte]

  has_many :questions, dependent: :destroy
  has_many :answers, dependent: :destroy
  has_many :rewards, dependent: :destroy
  has_many :votes, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :authorizations, dependent: :destroy
  has_many :subscriptions, dependent: :destroy

  def author?(object)
    id == object.user_id
  end

  def self.find_for_oauth(auth)
    FindForOauthService.new(auth).call
  end

  def create_authorization(auth)
    authorizations.create(provider: auth.provider, uid: auth.uid)
  end

  def subscribed?(question)
    subscriptions.where(question_id: question.id).any?
  end
end

app/models/vote.rb
# frozen_string_literal: true

class Vote < ApplicationRecord
  belongs_to :votable, polymorphic: true, touch: true
  belongs_to :user, touch: true

  validates :user, presence: true, uniqueness: { scope: %i[votable_id votable_type] }
  validates :vote, presence: true
end

app/controllers/users_controller.rb
# frozen_string_literal: true

class UsersController < ApplicationController
  def recieve_email
    @user = User.new
  end

  def set_email
    new_user
    redirect_to root_path, alert: 'Account created! We sended a message to your email to address confirmation.'
  rescue StandardError => e
    redirect_to root_path, alert: e.message.to_s
  end

  private

  def new_user
    password = Devise.friendly_token[0, 20]
    user = User.create!(
      email: email_params[:email],
      password: password,
      password_confirmation: password
    )
    user.authorizations.create(provider: session[:auth]['provider'], uid: session[:auth]['uid'])
  end

  def email_params
    params.require(:user).permit(:email)
  end
end

app/helpers/answers_helper.rb
# frozen_string_literal: true

module AnswersHelper
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
  def collection_cache_key_for(model)
    klass = model.to_s.capitalize.constantize
    count = klass.count
    max_updated_at = klass.maximum(:updated_at).try(:utc).try(:to_s, :number)
    "#{model.to_s.pluralize}/collection-#{count}-#{max_updated_at}"
  end
end

app/helpers/attachments_helper.rb
# frozen_string_literal: true

module AttachmentsHelper
end

app/helpers/comments_helper.rb
# frozen_string_literal: true

module CommentsHelper
end

app/helpers/questions_helper.rb
# frozen_string_literal: true

module QuestionsHelper
end

app/helpers/rewards_helper.rb
# frozen_string_literal: true

module RewardsHelper
end

app/helpers/searchs_helper.rb
# frozen_string_literal: true

module SearchsHelper
end

app/helpers/users_helper.rb
# frozen_string_literal: true

module UsersHelper
end

app/views/layouts/application.html.slim
doctype html
html
  head 
    title StackClone 
    meta name="viewport" content="width=device-width,initial-scale=1"
      =Gon::Base.render_data
      = csrf_meta_tags
      = action_cable_meta_tag
      = csp_meta_tag

      = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
      = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
      link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous"
      link rel="stylesheet" href="https://pro.fontawesome.com/releases/v5.10.0/css/all.css" integrity="sha384-AYmEC3Yw5cVb3ZcuHtOA93w35dYTsvhLPVnYs9eStHfGJvOvKxVfELGroGkvsg+p" crossorigin="anonymous"

  body
    .container
      = render 'shared/nav'
      p class="notice"
        = notice
      p class="alert"
        = alert
      br
      = yield
      br
      = render 'shared/footer'

    script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"
    script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"

app/views/shared/_errors.html.slim
- if resource&.errors.present?
  b= "#{resource.errors.count} error(s) detected"
  ul
   -resource.errors.full_messages.each do |message|
      li= message

app/views/shared/_footer.html.slim
- cache do
  .footer.bg-light.text-black
    .container
      .row
        .col-md-3
          .fa.fa-envelope
          = mail_to "alexxxicus@gmail.com"
        .col-md-3
        .col-md-3
        .col-md-3
          span Copyright 
          em = Time.now.year

app/views/shared/_link.html.slim
  - resource.links.each do |link|
    - if link.gist?
      = link_to link.name, link.url, class: 'gist', data: {gist_file: "#{link.url}"}
    - else
      li
        = link_to link.name, link.url

app/views/shared/_link_fields.html.slim
.nested-fields
  .field
    = f.label :name, 'Link name'
    br
    = f.text_field :name, class: 'form-control'
  .field
    = f.label :url
    = f.text_field :url, class: 'form-control'
  = link_to_remove_association "remove link", f, class: 'btn btn-sm btn-danger btn-block'

app/views/shared/_nav.html.slim
nav.navbar.navbar-expand-lg.navbar-light.bg-light
  = link_to 'QnA', root_path,  class: 'navbar-brand'
  ul.nav.mr-auto
    li.nav-item
      = link_to "Questions", questions_path, class: 'nav-link'
    - if current_user
      li.nav-item
        = link_to "My rewards", rewards_path, class: 'nav-link'

  .form-inline.my-2.my-lg-0
    = render 'searchs/form'
    - if current_user
      span.nav-link= current_user.email
      = link_to "Log out", destroy_user_session_path, method: :delete, class: 'btn btn-sm btn-danger mr-2'
    - else
      = link_to "Login", new_user_session_path, class: 'btn btn-sm btn-danger mr-2'
      = link_to "Register", new_user_registration_path , class: 'btn btn-sm btn-danger mr-2'

app/views/shared/_vote.html.slim
- cache resource
  span.text-center  Rating:
  div
    -if !current_user&.author?(resource) && current_user
      span class="rating_buttons_#{resource.name_id}"
        = link_to polymorphic_path(resource, action: :vote_up),
                  method: :patch,
                  remote: true,
                  class: 'rating-link',
                  id: "vote_up_#{resource.class.name.downcase}_#{resource.id}" do
                    i.fas.fa-caret-up
    span id="rating_#{resource.name_id}" title='Tap once again to cancel vote'
      = resource.rating
    -if !current_user&.author?(resource) && current_user
      span class="rating_buttons_#{resource.name_id}"
        = link_to polymorphic_path(resource, action: :vote_down),
                  method: :patch,
                  remote: true,
                  class: 'rating-link',
                  id: "vote_down_#{resource.class.name.downcase}_#{resource.id}"  do
                    i.fas.fa-caret-down