config/routes.rb
# frozen_string_literal: true

require 'sidekiq/web'

Rails.application.routes.draw do
  authenticate :user, ->(u) { u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  use_doorkeeper
  devise_for :users, controllers: { omniauth_callbacks: 'oauth_callbacks' }

  root to: 'questions#index'

  get '/user/recieve_email', to: 'users#recieve_email', as: 'recieve_email'
  post '/user/set_email', to: 'users#set_email', as: 'set_email'
  get '/search', to: 'searchs#search'

  concern :voted do
    member do
      patch :vote_up
      patch :vote_down
    end
  end

  resources :attachments, only: %i[destroy]

  resources :rewards, only: %i[index]

  resources :questions, concerns: [:voted] do
    resources :answers, concerns: [:voted], shallow: true do
      patch :mark_as_best, on: :member
      resources :comments, only: %i[create destroy], defaults: { commentable: 'answer' }
    end
    resources :comments, only: %i[create destroy], defaults: { commentable: 'question' }
    resources :subscriptions, only: %i[create destroy], shallow: true
  end

  namespace :api do
    namespace :v1 do
      resources :profiles, only: %i[index] do
        get :me, on: :collection
      end

      resources :questions do
        resources :answers, shallow: true
      end
    end
  end

  mount ActionCable.server => '/cable'
end

app/models/answer.rb
# frozen_string_literal: true

class Answer < ApplicationRecord
  include Linkable
  include Votable
  include Commentable

  belongs_to :question, touch: true
  belongs_to :user, touch: true

  has_many_attached :files

  validates :body, presence: true

  after_create :new_answer_notification

  private

  def new_answer_notification
    NotificationJob.perform_later(self)
  end
end

app/controllers/answers_controller.rb
# frozen_string_literal: true

class AnswersController < ApplicationController
  include Voted

  before_action :authenticate_user!, except: %i[show]
  before_action :load_answers, only: %i[create update]
  after_action :publish_answer, only: [:create]
  helper_method :answer, :question

  def show; end

  def new; end

  def edit; end

  def create
    @question = answer.question
    @answer = question.answers.new(answer_params)
    @answer.user = current_user
    @answer.save
  end

  def update
    answer.update(answer_params)
  end

  def destroy
    question.update!(best_answer: nil) if question.best_answer == answer
    answer.destroy
  end

  def mark_as_best
    answer
    @question = answer.question
    @question.mark_as_best(answer)
    load_answers
  end

  private

  def publish_answer
    return if @answer.errors.any?

    ActionCable.server.broadcast("questions/#{@answer.question_id}",
                                 answer: @answer,
                                 email: @answer.user.email,
                                 created_at: @answer.created_at.strftime('%d.%m.%Y %H:%M:%S'),
                                 links: @answer.links)
  end

  def load_answers
    @best_answer ||= question.best_answer
    @other_answers ||= question.other_answers
  end

  def answer
    @answer ||= params[:id] ? Answer.with_attached_files.find(params[:id]) : Answer.new
  end

  def question
    @question ||= params[:question_id] ? Question.find(params[:question_id]) : answer.question
  end

  def answer_params
    params.require(:answer).permit(:body,
                                   files: [],
                                   links_attributes: %i[id name url _destroy done])
  end
end

app/controllers/api/v1/answers_controller.rb
# frozen_string_literal: true

module Api
  module V1
    class AnswersController < Api::V1::BaseController
      helper_method :question, :answer

      authorize_resource class: Answer

      def index
        @answers = question.answers
        render json: @answers
      end

      def show
        render json: answer
      end

      def create
        @answer = question.answers.new(answer_params)
        @answer.user = current_resource_owner
        if @answer.save
          render json: @answer
        else
          render json: { errors: @answer.errors }, status: :unprocessable_entity
        end
      end

      def update
        if answer.update(answer_params)
          render json: answer
        else
          render json: { errors: answer.errors }, status: :unprocessable_entity
        end
      end

      def destroy
        authorize! :destroy, answer
        if answer.destroy
          head :ok
        else
          render json: { errors: answer.errors }, status: :unprocessable_entity
        end
      end

      private

      def answer
        @answer ||= params[:id] ? Answer.with_attached_files.find(params[:id]) : Answer.new
      end

      def question
        @question ||= params[:question_id] ? Question.find(params[:question_id]) : answer.question
      end

      def answer_params
        params.require(:answer).permit(:body)
      end
    end
  end
end

app/helpers/answers_helper.rb
# frozen_string_literal: true

module AnswersHelper
end

app/views/answers/_answer.html.slim
p= answer.body

.links
  p Links:
  ul
    - answer.links.each do |link|
      li= link_to link.name, link.url

- if user_signed_in?
  p= link_to 'Edit', '#', class: 'edit-answer-link', data: { answer_id: answer.id }

= form_with model: answer, class: 'hidden', html: { id: "edit-answer-#{answer.id}" } do |f|
  = f.label :body, 'Your answer'
  = f.text_area :body
  = f.submit 'Save'

app/views/answers/_answers.html.slim
- if best_answer.present?
  .row.rounded-lg.border.border-success
    .col-sm-12
      .best_answer
        = content_tag :div, id: "answer_#{best_answer.id}", class: 'mt-3'
          = render 'answers/body_of_answers', answer: @best_answer, best: true

- if other_answers.present?
  - other_answers.map do |answer|
    = content_tag :div, id: "answer_#{answer.id}", class: 'mt-3'
      .row
        .col-sm-12
          .card
            = render 'answers/body_of_answers', answer: answer, best: false

app/views/answers/_body_of_answers.html.slim
div class = "answer-#{answer.id}"
  li.list-group-item
    .row
      .col-2.border-right
        = render 'shared/vote', resource: answer
      - cache ['body_for', answer] do
        .col-10
          = answer.body
          ul
            = render 'attachments/attachments', resource: answer, edit_path: true
            = render 'shared/link', resource: answer
  .row
      .col-2
      .col-10
        hr
        .answer_comments
          = render 'comments/comments', resource: answer
          br
          - if can? :create, Comment
              = render 'comments/form', resource: answer

  - if best
    = render 'rewards/reward', resource: answer.question.reward 

  - if current_user&.author?(answer.question) && @question.best_answer != answer
    = link_to 'Best', mark_as_best_answer_path(answer), id: "best_#{answer.id}",class: 'btn btn-outline-success btn-sm', method: :patch, remote: true
  
  - if can? :update, answer
    - cache ['edit_form_for', answer] do
      = link_to 'Edit', '#', class: 'btn btn-outline-warning btn-sm edit-answer-link', data: { answer_id: answer.id}
      = link_to 'Delete answer', answer_path(answer), method: :delete, class: 'btn btn-outline-danger btn-sm', remote: true
      br

      = form_with model: answer, local: false, class: 'hidden', html: {id: "edit-answer-#{answer.id}"} do |f|
        p 
          = f.label :body, 'Your answer'
          = f.text_area :body, class: 'form-control'
        p  
          = f.label :files
          = f.file_field :files, class: 'form-control-file',multiple: true
        p Links :
        .links
          = link_to_add_association 'add link', f, :links, partial: 'shared/link_fields', class: 'btn btn-sm btn-success'
        
        p = f.submit 'Save'

app/views/answers/_form.html.slim
= form_with model: [question, @answer], data: { type: :json }, local: false  do |f|
  div 
    = f.label :body, 'Create your answer'
    = f.text_area :body, class: 'form-control'
  .row
    hr
    .col-6
      = f.label :files_new
      = f.file_field :files, class: 'form-control-file', multiple: true
    .col-6  
      p Links
      #links
        = f.fields_for :links do |link|
        .links
          = link_to_add_association 'add link', f, :links, partial: 'shared/link_fields', class: 'btn btn-outline-success btn-sm'
  p = f.submit 'Send answer'

app/views/answers/create.js.erb
$('.answer-errors').html("<%= render 'shared/errors', resource: @answer %>");
<% if @answer.persisted? %>
  $('.answers').html('<%= j render 'answers/answers', best_answer: @best_answer, other_answers: @other_answers %>');
  $('.new-answer #answer_body').val('');
  $('.new-answer #answer_files').val('');
<%end%>

app/views/answers/destroy.js.erb
document.getElementById('<%= dom_id(@answer) %>').remove();

app/views/answers/mark_as_best.js.erb
$('.answers').html('<%= j render 'answers/answers', best_answer: @best_answer, other_answers: @other_answers %>');

app/views/answers/update.js.erb
$('.answer-errors').html("<%= render 'shared/errors', resource: @answer %>");
<% unless @answer.errors.present? %>
  $('.answers').html('<%= j render 'answers/answers', best_answer: @best_answer, other_answers: @other_answers %>');
<% end %>